name: Create envfile

on: [push]

 jobs:    
     create-envfile:
           runs-on: ubuntu-latest
           steps:
              - name: Env create
                run: |
                   touch .env
                        echo SECRET_KEY="q^p9eee+l$#mh6#c@#^eqno!j-e#8-$aq6(z9xbrqwep53dejiomv#" >> .env
