name: Create envfile

on: [push]

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Create env file"
        run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          cat .env
